[window]
dimensions = {columns=100,lines=40}
opacity = 0.8

[font]
normal= {family="Hack", style="Regular"}


[colors]
[colors.primary]
background = '#1D1F21'
foreground = '#C5C8C6'

[colors.cursor]
text = '#1D1F21'
cursor = '#C5C8C6'

[colors.normal]
black   = '#1D1F21'
red     = '#CC6666'
green   = '#B5BD68'
yellow  = '#F0C674'
blue    = '#81A2BE'
magenta = '#B294BB'
cyan    = '#8ABEB7'
white   = '#C5C8C6'

[colors.bright]
black   = '#969896'
red     = '#CC6666'
green   = '#B5BD68'
yellow  = '#F0C674'
blue    = '#81A2BE'
magenta = '#B294BB'
cyan    = '#8ABEB7'
white   = '#FFFFFF'

